=== cbeams/spring-framework-2.5.x/src/org/springframework/beans/factory/xml/spring-beans.dtd
<!--
	Spring XML BeanFactory DTD.
	Author: Rod Johnson
	
	This defines a simple and consistent way of creating a namespace
	of JavaBeans configured by a Spring XmlBeanFactory.
	
	This document type is used by most Spring functionality, including
	web application contexts, which are based on BeanFactories.
	
	Each <bean> element in this document defines a JavaBean.
	Typically the bean class is specified, along with JavaBean
	properties.
	
	References among beans are supported (setting a JavaBean
	property to refer to another bean in the same factory).
	
	Bean instances can be "singletons" (shared instances)
	or "prototypes" (independent instances).
	
	There is also support for lists, maps, and 
	java.util.Properties types.
	
	As the format is simple, a DTD is sufficient, and there's
	no need for a schema at this point.
	
	$Id: spring-beans.dtd,v 1.4 2003-10-16 18:56:41 jhoeller Exp $
-->

<!-- 
	The document root.
	At least one bean definition is required.
-->

<!ELEMENT beans (
        bean+
)>

<!--
	Defines a single named bean.
-->
<!ELEMENT bean (
        property*
)>

<!--
	All beans are identified by an id, to enable reference checking.
	There are constraints on a valid XML id: if you want to reference
	your bean in Java code using a name that's illegal as an XML id,
	use the optional "name" attribute.
-->
<!ATTLIST bean id ID #REQUIRED>

<!-- 
	Each bean definition must specify the FQN of the class,
	or the name of the parent bean from which the class can be worked out.
-->
<!ATTLIST bean class CDATA #IMPLIED>
<!ATTLIST bean parent CDATA #IMPLIED>

<!--
	Optional attribute controlling whether to check whether all this
	beans dependencies, expressed in its properties, are satisfied.
	Default is no dependency checking.
	"simple" type dependency checking includes primitives and String
	"object" includes collaborators (other beans in the factory)
	"all" includes both types of dependency checking
	
-->
<!ATTLIST bean dependency-check (none|objects|simple|all) "none">

<!--
	Optional attribute controlling whether to "autowire"
	bean properties. This is an automagical process in which bean references
	don't need to be coded explicitly in the XML bean definition file,
	but Spring works out dependencies.
	
	There are three modes:
	
	1. no
	The traditional Spring default. No automagical wiring. Bean references
	must be defined in the XML file via the <ref> element. We recommend this
	in most cases as it makes documentation more explicit.
	
	2. byName
	Autowiring by property name. If a bean of class Cat exposes a dog property,
	Spring will try to set this to the value of the bean "dog" in the current
	factory.
	
	3. byType
	This is like the PicoContainer default, in which there must be exactly
	one bean of the property type in the bean factory. If there are 0 or
	more than one, a fatal error is raised, and you can't use byType autowiring for
	that bean.
	This makes bean factories simple to configure for small namespaces,
	but doesn't work as well as standard Spring behaviour for
	bigger applications.
	
	Autowire behaviour can be combined with dependency checking, which will
	be performed after all auto wiring has been completed.
-->
<!ATTLIST bean autowire (no|byName|byType) "no"> 

<!-- 
	Optional attribute for the name of the custom initialization method
	to invoke after setting bean properties. The method must have no arguments,
	but may throw any exception. 
-->
<!ATTLIST bean init-method CDATA #IMPLIED>

<!--
	Optional attribute for the name of the custom destroy method to invoke
	on bean factory shutdown. The method must have no arguments,
	but may throw any exception. Note: Only invoked on singleton beans!
-->
<!ATTLIST bean destroy-method CDATA #IMPLIED>

<!--
	Is this bean a "singleton" (one shared instance, which will
	be returned by all calls to getBean() with the id),
	or a "prototype" (independent instance resulting from each call to
	getBean(). Default is singleton.

	Singletons are most commonly used, and are ideal for multi-threaded
	service objects.
-->
<!ATTLIST bean singleton (true|false) "true"> 

<!--
	Optional. Can be used to create an alias illegal in an id.
-->
<!ATTLIST bean name CDATA #IMPLIED>

<!--
	Bean definitions can have zero or more properties. 
	Property elements correspond to JavaBean setter methods exposed
	by the bean classes. Spring supports primitives, references to other
	beans in the same or related factories, lists, maps and properties.
-->
<!ELEMENT property (
        (value | ref | list | map | props)
)>

<!--
	The property name attribute is the name of the JavaBean property.
	This follows JavaBean conventions: a name of "age" would correspond
	to setAge()/optional getAge() methods.
-->
<!ATTLIST property name CDATA #REQUIRED>

<!--
	Defines a reference to another bean in this factory or an external
	factory (parent or included factory). 
-->
<!ELEMENT ref EMPTY>

<!--
	Contains a string representation of a property value.
	The property may be a string, or may be converted to the
	required type using the JavaBeans PropertyEditor
	machinery. This makes it possible for application developers
	to write custom PropertyEditor implementations that can
	convert strings to objects. 
	
	Note that this is recommended for simple objects only.
	Configure more complex objects by setting JavaBean
	properties to references to other beans.
-->
<!ELEMENT value (#PCDATA)>

<!-- 
	References must specify the id of the target bean.
	Internal references, using
	the "bean" attribute, can be checked by this DTD,
	thus should be preferred for references within the same
	bean factory XML file.
	External references must use the "external" attribute and can
	be checked only at runtime.
-->
<!ATTLIST ref bean IDREF #IMPLIED>
<!ATTLIST ref external CDATA #IMPLIED>

<!--
	A list can contain multiple value and/or ref elements.
	Java lists are untyped, pending generics support in Java 1.5. 
	although references will be strongly typed. 
	A list can also map to an array type. The necessary conversion
	is automatically performed by the Spring AbstractBeanFactory. 
-->
<!ELEMENT list (
        (value | ref)*
)>

<!--
	A Spring map is a mapping from a string key to 
	object.
	Maps may be empty.
-->
<!ELEMENT map (
        (entry)*
)>

<!--
	A map entry can be a value, ref or list
	The name of the property is given by the "key" attribute.
-->
<!ELEMENT entry (
        (value | ref | list)*
)>

<!ATTLIST entry key CDATA #REQUIRED>

<!--
	Props elements differ from map elements in that values must be strings.
	Props may be empty.
-->
<!ELEMENT props (
        (prop)*
)>

<!--
	Element content is the string value of the property. The "key"
	attribute is the name of the property.
-->
<!ELEMENT prop
        (#PCDATA)
>

<!--
	Each property element must specify the key. The value
	is the element content.
-->
<!ATTLIST prop key CDATA #REQUIRED>

=== cbeams/spring-framework-2.5.x/samples/jpetstore/client/clientContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
  - Application context for the remote OrderService client.
	- Defines various OrderService proxies to be called by OrderServiceClient.
	-->
<beans>

	<!-- Resolves ${...} placeholders from client.properties -->
	<bean id="propertyConfigurer" class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
		<property name="location"><value>client.properties</value></property>
	</bean>

	<!-- Proxy for the Hessian-exported OrderService -->
	<!-- Hessian is a slim binary HTTP remoting protocol -->
	<bean id="hessianProxy" class="org.springframework.remoting.caucho.HessianProxyFactoryBean">
		<property name="serviceUrl">
			<value>http://${serverName}:${httpPort}${contextPath}/remoting/OrderService-hessian</value>
		</property>
		<property name="serviceInterface">
			<value>org.springframework.samples.jpetstore.domain.logic.OrderService</value>
		</property>
	</bean>

	<!-- Proxy for the Burlap-exported OrderService -->
	<!-- Burlap is a slim XML-based HTTP remoting protocol -->
	<bean id="burlapProxy" class="org.springframework.remoting.caucho.BurlapProxyFactoryBean">
		<property name="serviceUrl">
			<value>http://${serverName}:${httpPort}${contextPath}/remoting/OrderService-burlap</value>
		</property>
		<property name="serviceInterface">
			<value>org.springframework.samples.jpetstore.domain.logic.OrderService</value>
		</property>
	</bean>

	<!-- Proxy for the HTTP-invoker-exported OrderService -->
	<!-- Spring's HTTP invoker uses Java serialization via HTTP  -->
	<bean id="httpInvokerProxy" class="org.springframework.remoting.httpinvoker.HttpInvokerProxyFactoryBean">
		<property name="serviceUrl">
			<value>http://${serverName}:${httpPort}${contextPath}/remoting/OrderService-httpinvoker</value>
		</property>
		<property name="serviceInterface">
			<value>org.springframework.samples.jpetstore.domain.logic.OrderService</value>
		</property>
	</bean>

	<!-- Proxy for the JAX-RPC/Axis-exported OrderService -->
	<bean id="jaxRpcProxy" class="org.springframework.remoting.jaxrpc.JaxRpcPortProxyFactoryBean">
		<property name="serviceFactoryClass">
			<value>org.apache.axis.client.ServiceFactory</value>
		</property>
		<property name="wsdlDocumentUrl">
			<value>http://${serverName}:${httpPort}${contextPath}/axis/OrderService?wsdl</value>
		</property>
		<property name="namespaceUri">
			<value>http://${serverName}:${httpPort}${contextPath}/axis/OrderService</value>
		</property>
		<property name="serviceName">
			<value>JaxRpcOrderServiceService</value>
		</property>
		<property name="servicePostProcessors">
			<list>
				<bean class="org.springframework.samples.jpetstore.service.client.BeanMappingServicePostProcessor"/>
			</list>
		</property>
		<property name="portName">
			<value>OrderService</value>
		</property>
		<property name="serviceInterface">
			<value>org.springframework.samples.jpetstore.domain.logic.OrderService</value>
		</property>
		<!--
		If you want to work with a JAX-RPC port stub underneath, you need to specify
		the RMI interface to use at the JAX-RPC port level. This might give advantages
		on certain JAX-RPC implementations. If not specified, JAX-RPC dynamic calls
		will be used, which has been tested to work nicely on Apache Axis.
		-->
		<!--
		<property name="portInterface">
			<value>org.springframework.samples.jpetstore.service.RemoteOrderService</value>
		</property>
		-->
	</bean>

	<!-- Proxy for the RMI-exported OrderService -->
	<!-- Commented out by default to avoid conflicts with EJB containers -->
	<!--
	<bean id="rmiProxy" class="org.springframework.remoting.rmi.RmiProxyFactoryBean">
		<property name="serviceUrl">
			<value>rmi://${serverName}:${rmiPort}/order</value>
		</property>
		<property name="serviceInterface">
			<value>org.springframework.samples.jpetstore.domain.logic.OrderService</value>
		</property>
	</bean>
	-->

</beans>

=== cbeams/spring-framework-2.5.x/samples/webflow/flowlauncher/web/WEB-INF/dispatcher-servlet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>

	<bean id="viewResolver" class="org.springframework.web.servlet.view.InternalResourceViewResolver">
		<property name="prefix"><value>/WEB-INF/jsp/</value></property>
		<property name="suffix"><value>.jsp</value></property>
	</bean>

	<bean id="frontController" name="/flow.htm" class="org.springframework.web.flow.mvc.FlowController">
		<property name="cacheSeconds"><value>5</value></property>
		<property name="flowExecutionManager">
			<bean class="org.springframework.web.flow.execution.servlet.ServletFlowExecutionManager">
				<property name="storage">
					<bean class="org.springframework.web.flow.execution.servlet.SessionContinuationFlowExecutionStorage"/>
				</property>
				<property name="listener">
					<bean class="org.springframework.samples.flowlauncher.SampleFlowExecutionListener"/>
				</property>
			</bean>
		</property>
	</bean>

	<bean id="sampleA" class="org.springframework.web.flow.config.XmlFlowFactoryBean">
		<property name="location" value="/WEB-INF/sampleA-flow.xml"/>
	</bean>

	<bean id="sampleB" class="org.springframework.web.flow.config.XmlFlowFactoryBean">
		<property name="location" value="/WEB-INF/sampleB-flow.xml"/>
	</bean>

</beans>

=== cbeams/spring-framework-2.5.x/test/org/springframework/aop/framework/autoproxy/metadata/enterpriseServices.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC  "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
	Common bean definitions for EnterpriseServices
	tests.
-->
<beans>

<bean id="enterpriseServices" 
		class="org.springframework.aop.framework.autoproxy.DefaultAdvisorAutoProxyCreator">
	
	<!-- Change default exclusion prefix -->
	<property name="usePrefix"><value>true</value></property>
	<property name="advisorBeanNamePrefix"><value>es.</value></property>
		
		<property name="customTargetSourceCreators">
			<list>
				<ref local="es.poolingTargetSourceCreator" />
				<ref local="es.prototypeTargetSourceCreator" />
				<ref local="es.threadLocalTargetSourceCreator" />
			</list>
		</property>
	</bean>
	
	<bean id="es.poolingTargetSourceCreator"
		class="org.springframework.aop.framework.autoproxy.metadata.AttributesPoolingTargetSourceCreator"
		autowire="constructor" >
	</bean>

	<bean id="es.txManager"
		class="org.springframework.transaction.CountingTxManager">
	</bean>
	
	<bean id="es.TAS"
		class="org.springframework.transaction.interceptor.AttributesTransactionAttributeSource"
		autowire="constructor">
	</bean>
	
	<bean id="es.txAdviceInterceptor"
		class="org.springframework.transaction.interceptor.TransactionInterceptor">
		<property name="transactionManager"> <ref bean="es.txManager"/></property>
		<property name="transactionAttributeSource"><ref bean="es.TAS"/></property>
	</bean>
	
	<bean id="es.txAdvice"
		class="org.springframework.transaction.interceptor.TransactionAttributeSourceAdvisor"
		autowire="constructor" >
	</bean>
	
	<bean id="es.prototypeTargetSourceCreator"
		class="org.springframework.aop.framework.autoproxy.metadata.AttributesPrototypeTargetSourceCreator"
		autowire="constructor" >
	</bean>
	
	<bean id="es.threadLocalTargetSourceCreator"
		class="org.springframework.aop.framework.autoproxy.metadata.AttributesThreadLocalTargetSourceCreator"
		autowire="constructor" >
	</bean>
	
	
	<bean id="txClass"
		class="org.springframework.aop.framework.autoproxy.metadata.TxClassImpl">
	</bean>
	
	<bean id="txClassWithClassAttribute" singleton="false"
		class="org.springframework.aop.framework.autoproxy.metadata.TxClassWithClassAttribute">
	</bean>
	
	<bean id="noProxy"
		class="org.springframework.beans.TestBean">
	</bean>
	
	
	
	<!--
		Must NOT be a singleton. Used in stateful introductions.
	-->
	<bean id="es.modifiableAdvice"
		class="org.springframework.aop.framework.autoproxy.metadata.ModifiableAdvisor"
		singleton="false"
	>
		<property name="attributes"><ref bean="attributes"/></property>
	</bean>
	
	<bean id="modifiable1"
		class="org.springframework.aop.framework.autoproxy.metadata.ModifiableTestBean" />

	
	<bean id="modifiable2"
		class="org.springframework.aop.framework.autoproxy.metadata.ModifiableTestBean" />
	
	
	<bean id="protoTest"
		class="org.springframework.aop.framework.autoproxy.metadata.PrototypeTestBean" 
		singleton="false">
	</bean>
	
	<bean id="threadLocalTest"
		class="org.springframework.aop.framework.autoproxy.metadata.ThreadLocalTestBean" 
		singleton="false">
	</bean>
	
	<!-- Should not be proxied -->
	<bean id="rawTest"
		singleton="false"
		class="org.springframework.beans.TestBean" >
	</bean>
	

</beans>

=== cbeams/spring-framework-2.5.x/test/org/springframework/beans/factory/config/ObjectFactoryCreatingFactoryBeanTests.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC  "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
  Test data for ObjectFactoryCreatingFactoryBeanTests
-->

<beans>
	
  <bean id="prototypeTarget" class="java.util.Date" singleton="false">
  </bean> 	

  <bean id="prototype" class="org.springframework.beans.factory.config.ObjectFactoryCreatingFactoryBean">
   <property name="targetBeanName"><idref local="prototypeTarget"/></property>
  </bean> 
  
  <bean id="testBean" class="org.springframework.beans.factory.config.ObjectFactoryCreatingFactoryBeanTests$TestBean">
   <property name="objectFactory"><ref local="prototype"/></property>
  </bean>
  
</beans>

=== cbeams/spring-framework-2.5.x/tiger/test/org/springframework/aop/aspectj/autoproxy/aspectsPlusAdvisor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd"
>

<beans>

	<bean 
		class="org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator" />

	<bean 
		class="org.springframework.aop.aspectj.autoproxy.MultiplyReturnValue" >
		<property name="multiple" value="3" />
	</bean>
		
	<bean id="adrian" class="org.springframework.beans.TestBean">
		<property name="name" value="Adrian" />
		<property name="age" value="34" />
	</bean>
	
	
	<bean 
		class="org.springframework.aop.aspectj.autoproxy.TestBeanAdvisor" />
	
</beans>

=== cbeams/spring-framework-2.5.x/samples/jpetstore/war/WEB-INF/petstore-servlet.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
  - DispatcherServlet application context for the Spring web MVC
	- implementation of JPetStore's web tier.
	-->
<beans>

	<!-- ========================= VIEW DEFINITIONS ========================= -->

	<bean id="viewResolver" class="org.springframework.web.servlet.view.InternalResourceViewResolver">
		<property name="viewClass"><value>org.springframework.web.servlet.view.JstlView</value></property>
		<property name="prefix"><value>/WEB-INF/jsp/spring/</value></property>
		<property name="suffix"><value>.jsp</value></property>
	</bean>


	<!-- ========================= DEFINITIONS OF PUBLIC CONTROLLERS ========================= -->

	<bean id="defaultHandlerMapping" class="org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping"/>

	<bean name="/shop/addItemToCart.do" class="org.springframework.samples.jpetstore.web.spring.AddItemToCartController">
		<property name="petStore"><ref bean="petStore"/></property>
	</bean>

	<bean name="/shop/checkout.do" class="org.springframework.samples.jpetstore.web.spring.ViewCartController">
		<property name="successView"><value>Checkout</value></property>
	</bean>

	<bean name="/shop/index.do" class="org.springframework.web.servlet.mvc.ParameterizableViewController">
		<property name="viewName"><value>index</value></property>
	</bean>

	<bean name="/shop/newAccount.do" class="org.springframework.samples.jpetstore.web.spring.AccountFormController">
		<property name="petStore"><ref bean="petStore"/></property>
		<property name="validator"><ref bean="accountValidator"/></property>
		<property name="successView"><value>index</value></property>
	</bean>

	<bean name="/shop/removeItemFromCart.do" class="org.springframework.samples.jpetstore.web.spring.RemoveItemFromCartController"/>

	<bean name="/shop/signoff.do" class="org.springframework.samples.jpetstore.web.spring.SignoffController"/>

	<bean name="/shop/searchProducts.do" class="org.springframework.samples.jpetstore.web.spring.SearchProductsController">
		<property name="petStore"><ref bean="petStore"/></property>
	</bean>

	<bean name="/shop/signon.do" class="org.springframework.samples.jpetstore.web.spring.SignonController">
		<property name="petStore"><ref bean="petStore"/></property>
	</bean>

	<bean name="/shop/signonForm.do" class="org.springframework.web.servlet.mvc.ParameterizableViewController">
		<property name="viewName"><value>SignonForm</value></property>
	</bean>

	<bean name="/shop/updateCartQuantities.do" class="org.springframework.samples.jpetstore.web.spring.UpdateCartQuantitiesController"/>

	<bean name="/shop/viewCart.do" class="org.springframework.samples.jpetstore.web.spring.ViewCartController">
		<property name="successView"><value>Cart</value></property>
	</bean>

	<bean name="/shop/viewCategory.do" class="org.springframework.samples.jpetstore.web.spring.ViewCategoryController">
		<property name="petStore"><ref bean="petStore"/></property>
	</bean>

	<bean name="/shop/viewItem.do" class="org.springframework.samples.jpetstore.web.spring.ViewItemController">
		<property name="petStore"><ref bean="petStore"/></property>
	</bean>

	<bean name="/shop/viewProduct.do" class="org.springframework.samples.jpetstore.web.spring.ViewProductController">
		<property name="petStore"><ref bean="petStore"/></property>
	</bean>


	<!-- ========================= DEFINITIONS OF PROTECTED CONTROLLERS ========================= -->

	<bean id="secureHandlerMapping" class="org.springframework.web.servlet.handler.SimpleUrlHandlerMapping">
		<property name="interceptors">
			<list>
				<ref bean="signonInterceptor"/>
			</list>
		</property>
		<property name="urlMap">
			<map>
				<entry key="/shop/editAccount.do"><ref local="secure_editAccount"/></entry>
				<entry key="/shop/listOrders.do"><ref local="secure_listOrders"/></entry>
				<entry key="/shop/newOrder.do"><ref local="secure_newOrder"/></entry>
				<entry key="/shop/viewOrder.do"><ref local="secure_viewOrder"/></entry>
			</map>
		</property>
	</bean>

	<bean id="signonInterceptor" class="org.springframework.samples.jpetstore.web.spring.SignonInterceptor"/>

	<bean id="secure_editAccount" class="org.springframework.samples.jpetstore.web.spring.AccountFormController">
		<property name="petStore"><ref bean="petStore"/></property>
		<property name="validator"><ref bean="accountValidator"/></property>
		<property name="successView"><value>index</value></property>
	</bean>

	<bean id="secure_listOrders" class="org.springframework.samples.jpetstore.web.spring.ListOrdersController">
		<property name="petStore"><ref bean="petStore"/></property>
	</bean>

	<bean id="secure_newOrder" class="org.springframework.samples.jpetstore.web.spring.OrderFormController">
		<property name="petStore"><ref bean="petStore"/></property>
		<property name="validator"><ref bean="orderValidator"/></property>
	</bean>

	<bean id="secure_viewOrder" class="org.springframework.samples.jpetstore.web.spring.ViewOrderController">
		<property name="petStore"><ref bean="petStore"/></property>
	</bean>

</beans>

=== cbeams/spring-framework-2.5.x/samples/tiles-example/war/WEB-INF/tiles-servlet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>

	<bean id="viewResolver" class="org.springframework.web.servlet.view.InternalResourceViewResolver">
		<property name="viewClass">
			<value>org.springframework.web.servlet.view.tiles.TilesJstlView</value>
		</property>
	</bean>
	

	<bean id="messageSource"
		class="org.springframework.context.support.ResourceBundleMessageSource">
        <property name="basename"><value>messages</value></property>                                                                           
    </bean>
	
	<bean id="tilesConfigurer" class="org.springframework.web.servlet.view.tiles.TilesConfigurer">
		<property name="definitions">
			<list>
				<value>/WEB-INF/defs/definitions.xml</value>
			</list>
		</property>
	</bean>

	<bean id="feedConfigurer" class="org.springframework.samples.tiles.NewsFeedConfigurer">
		<property name="feeds">
			<props>
				<prop key="theserverside">http://www.theserverside.com/rss/theserverside-1.0.rdf</prop>
				<prop key="slashdot">http://slashdot.org/slashdot.rss</prop>				
				<prop key="javablogs">http://www.javablogs.com/ViewDaysBlogs.action?view=rss</prop>								
			</props>
		</property>
	</bean>

	<bean id="urlMapping" class="org.springframework.web.servlet.handler.SimpleUrlHandlerMapping">
		<property name="mappings">
			<props>
				<prop key="/*.html">viewController</prop>
			</props>
		</property>
	</bean>

	<bean id="viewController" class="org.springframework.web.servlet.mvc.UrlFilenameViewController"/>

</beans>

=== cbeams/spring-framework-2.5.x/samples/petclinic/test/org/springframework/samples/petclinic/hibernate/applicationContext-hibernate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>

	<!-- ========================= GENERAL DEFINITIONS ========================= -->

	<!-- Message source for this context, loaded from localized "messages_xx" files -->
	<bean id="messageSource" class="org.springframework.context.support.ResourceBundleMessageSource">
		<property name="basename"><value>messages</value></property>										
	</bean>

	<!-- ========================= Start of PERSISTENCE DEFINITIONS ========================= -->
  
	<!-- NOTE: Choose exactly 1 "dataSource" bean and 1 "clinicTarget" bean -->

	<!-- Local HSQL DataSource that works in any environment -->
	<bean id="dataSource" class="org.springframework.jdbc.datasource.DriverManagerDataSource">
		<property name="driverClassName"><value>org.hsqldb.jdbcDriver</value></property>
		<property name="url"><value>jdbc:hsqldb:hsql://localhost:9001</value></property>
		<property name="username"><value>sa</value></property>
		<property name="password"><value></value></property>
	</bean>

	<!-- Hibernate SessionFactory for HSQL -->
	<bean id="sessionFactory" class="org.springframework.orm.hibernate.LocalSessionFactoryBean">
		<property name="dataSource"><ref local="dataSource"/></property>
		<property name="mappingResources">
			<value>org/springframework/samples/petclinic/hibernate/petclinic.hbm.xml</value>
		</property>
		<property name="hibernateProperties">
			<props>
				<prop key="hibernate.dialect">net.sf.hibernate.dialect.HSQLDialect</prop>
			</props>
		</property>
	</bean>

	<!-- Transaction manager for a single Hibernate SessionFactory (alternative to JTA) -->
	<bean id="transactionManager" class="org.springframework.orm.hibernate.HibernateTransactionManager">
		<property name="sessionFactory"><ref local="sessionFactory"/></property>
	</bean>

	<!-- Transactional proxy for the Petclinic primary business object -->
	<bean id="clinic" class="org.springframework.transaction.interceptor.TransactionProxyFactoryBean">
		<property name="transactionManager"><ref local="transactionManager"/></property>
		<property name="target"><ref local="clinicTarget"/></property>
		<property name="transactionAttributes">
			<props>
				<prop key="*">PROPAGATION_REQUIRED</prop>
			</props>
		</property>
	</bean>

	<!-- Petclinic primary business object: Hibernate implementation -->
	<bean id="clinicTarget" class="org.springframework.samples.petclinic.hibernate.HibernateClinic">
		<property name="sessionFactory"><ref local="sessionFactory"/></property>
	</bean>

	<!-- ========================= End of PERSISTENCE DEFINITIONS ========================= -->
	
</beans>
