=== cbeams/spring-framework-2.5.x/src/org/springframework/beans/factory/xml/spring-beans.dtd
<!--
	Spring XML BeanFactory DTD.
	Author: Rod Johnson
	
	This defines a simple and consistent way of creating a namespace
	of JavaBeans configured by a Spring XmlBeanFactory.
	
	This document type is used by most Spring functionality, including
	web application contexts, which are based on BeanFactories.
	
	Each <bean> element in this document defines a JavaBean.
	Typically the bean class is specified, along with JavaBean
	properties.
	
	References among beans are supported (setting a JavaBean
	property to refer to another bean in the same factory).
	
	Bean instances can be "singletons" (shared instances)
	or "prototypes" (independent instances).
	
	There is also support for lists, maps, and 
	java.util.Properties types.
	
	As the format is simple, a DTD is sufficient, and there's
	no need for a schema at this point.
	
	$Id: spring-beans.dtd,v 1.4 2003-10-16 18:56:41 jhoeller Exp $
-->

<!-- 
	The document root.
	At least one bean definition is required.
-->

<!ELEMENT beans (
        bean+
)>

<!--
	Defines a single named bean.
-->
<!ELEMENT bean (
        property*
)>

<!--
	All beans are identified by an id, to enable reference checking.
	There are constraints on a valid XML id: if you want to reference
	your bean in Java code using a name that's illegal as an XML id,
	use the optional "name" attribute.
-->
<!ATTLIST bean id ID #REQUIRED>

<!-- 
	Each bean definition must specify the FQN of the class,
	or the name of the parent bean from which the class can be worked out.
-->
<!ATTLIST bean class CDATA #IMPLIED>
<!ATTLIST bean parent CDATA #IMPLIED>

<!--
	Optional attribute controlling whether to check whether all this
	beans dependencies, expressed in its properties, are satisfied.
	Default is no dependency checking.
	"simple" type dependency checking includes primitives and String
	"object" includes collaborators (other beans in the factory)
	"all" includes both types of dependency checking
	
-->
<!ATTLIST bean dependency-check (none|objects|simple|all) "none">

<!--
	Optional attribute controlling whether to "autowire"
	bean properties. This is an automagical process in which bean references
	don't need to be coded explicitly in the XML bean definition file,
	but Spring works out dependencies.
	
	There are three modes:
	
	1. no
	The traditional Spring default. No automagical wiring. Bean references
	must be defined in the XML file via the <ref> element. We recommend this
	in most cases as it makes documentation more explicit.
	
	2. byName
	Autowiring by property name. If a bean of class Cat exposes a dog property,
	Spring will try to set this to the value of the bean "dog" in the current
	factory.
	
	3. byType
	This is like the PicoContainer default, in which there must be exactly
	one bean of the property type in the bean factory. If there are 0 or
	more than one, a fatal error is raised, and you can't use byType autowiring for
	that bean.
	This makes bean factories simple to configure for small namespaces,
	but doesn't work as well as standard Spring behaviour for
	bigger applications.
	
	Autowire behaviour can be combined with dependency checking, which will
	be performed after all auto wiring has been completed.
-->
<!ATTLIST bean autowire (no|byName|byType) "no"> 

<!-- 
	Optional attribute for the name of the custom initialization method
	to invoke after setting bean properties. The method must have no arguments,
	but may throw any exception. 
-->
<!ATTLIST bean init-method CDATA #IMPLIED>

<!--
	Optional attribute for the name of the custom destroy method to invoke
	on bean factory shutdown. The method must have no arguments,
	but may throw any exception. Note: Only invoked on singleton beans!
-->
<!ATTLIST bean destroy-method CDATA #IMPLIED>

<!--
	Is this bean a "singleton" (one shared instance, which will
	be returned by all calls to getBean() with the id),
	or a "prototype" (independent instance resulting from each call to
	getBean(). Default is singleton.

	Singletons are most commonly used, and are ideal for multi-threaded
	service objects.
-->
<!ATTLIST bean singleton (true|false) "true"> 

<!--
	Optional. Can be used to create an alias illegal in an id.
-->
<!ATTLIST bean name CDATA #IMPLIED>

<!--
	Bean definitions can have zero or more properties. 
	Property elements correspond to JavaBean setter methods exposed
	by the bean classes. Spring supports primitives, references to other
	beans in the same or related factories, lists, maps and properties.
-->
<!ELEMENT property (
        (value | ref | list | map | props)
)>

<!--
	The property name attribute is the name of the JavaBean property.
	This follows JavaBean conventions: a name of "age" would correspond
	to setAge()/optional getAge() methods.
-->
<!ATTLIST property name CDATA #REQUIRED>

<!--
	Defines a reference to another bean in this factory or an external
	factory (parent or included factory). 
-->
<!ELEMENT ref EMPTY>

<!--
	Contains a string representation of a property value.
	The property may be a string, or may be converted to the
	required type using the JavaBeans PropertyEditor
	machinery. This makes it possible for application developers
	to write custom PropertyEditor implementations that can
	convert strings to objects. 
	
	Note that this is recommended for simple objects only.
	Configure more complex objects by setting JavaBean
	properties to references to other beans.
-->
<!ELEMENT value (#PCDATA)>

<!-- 
	References must specify the id of the target bean.
	Internal references, using
	the "bean" attribute, can be checked by this DTD,
	thus should be preferred for references within the same
	bean factory XML file.
	External references must use the "external" attribute and can
	be checked only at runtime.
-->
<!ATTLIST ref bean IDREF #IMPLIED>
<!ATTLIST ref external CDATA #IMPLIED>

<!--
	A list can contain multiple value and/or ref elements.
	Java lists are untyped, pending generics support in Java 1.5. 
	although references will be strongly typed. 
	A list can also map to an array type. The necessary conversion
	is automatically performed by the Spring AbstractBeanFactory. 
-->
<!ELEMENT list (
        (value | ref)*
)>

<!--
	A Spring map is a mapping from a string key to 
	object.
	Maps may be empty.
-->
<!ELEMENT map (
        (entry)*
)>

<!--
	A map entry can be a value, ref or list
	The name of the property is given by the "key" attribute.
-->
<!ELEMENT entry (
        (value | ref | list)*
)>

<!ATTLIST entry key CDATA #REQUIRED>

<!--
	Props elements differ from map elements in that values must be strings.
	Props may be empty.
-->
<!ELEMENT props (
        (prop)*
)>

<!--
	Element content is the string value of the property. The "key"
	attribute is the name of the property.
-->
<!ELEMENT prop
        (#PCDATA)
>

<!--
	Each property element must specify the key. The value
	is the element content.
-->
<!ATTLIST prop key CDATA #REQUIRED>

=== cbeams/spring-framework-2.5.x/test/org/springframework/aop/framework/innerBeanTarget.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC  "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
	Test that inner bean for target means that we can use
	autowire without ambiguity from target and proxy.
	$Id: innerBeanTarget.xml,v 1.1 2004-06-18 10:56:54 johnsonr Exp $
-->

<beans>

	<bean id="nopInterceptor" class="org.springframework.aop.interceptor.NopInterceptor">
	</bean>
	
	<bean id="testBean"
		class="org.springframework.aop.framework.ProxyFactoryBean"
	> 
			<property name="target">
				<bean class="org.springframework.beans.TestBean">	
					<property name="name"><value>innerBeanTarget</value></property>
				</bean>
			</property>
			
			<property name="interceptorNames">
				<value>nopInterceptor</value>
			</property>
	</bean>
	
	<!--	
		Autowire would fail if distinct target and proxy:
		we expect just to have proxy
	-->
	<bean id="autowireCheck" 
		class="org.springframework.aop.framework.ProxyFactoryBeanTests$DependsOnITestBean"
			autowire="constructor" />
	
</beans>

=== cbeams/spring-framework-2.5.x/samples/webapp-typical/war/WEB-INF/example-servlet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
  - Application context definition for "example" DispatcherServlet.
  - Heavily depended on web infrastructure, naturally.
  -->

<beans>

	<!-- ========================= GENERAL DEFINITIONS ========================= -->

	<!--
	  - The message source for this servlet, loaded from localized "example-messages_xx"
	  - classpath files, i.e. "/WEB-INF/classes/example-messages.properties".
	  -
	  - "getMessage" calls to this context will use this source first, falling back to
	  - the root context's. This means that this child context inherits all messages
	  - from the parent's source, but is able to define new messages and override ones
	  - defined in the parent's source.
	  -->
	<bean id="messageSource" class="org.springframework.context.support.ResourceBundleMessageSource" >
		<property name="basename"><value>example-messages</value></property>
	</bean>

	<!--
	  - Locale resolution via cookie instead of evaluating the browser locale.
	  - Locale changes will send a new cookie to the client.
	  -->
	<bean id="localeResolver" class="org.springframework.web.servlet.i18n.CookieLocaleResolver"/>

	<!--
	  - Theme resolution via cookie instead of the fixed one named "theme".
	  - Theme changes will send a new cookie to the client.
	  -->
	<bean id="themeResolver" class="org.springframework.web.servlet.theme.CookieThemeResolver"/>


	<!-- ========================= MAPPING DEFINITIONS ========================= -->

	<!--
	 - Explicit URL handler mapping instead of default BeanNameUrlHandlerMapping.
	 -->
	<bean id="urlMapping" class="org.springframework.web.servlet.handler.SimpleUrlHandlerMapping">
		<property name="urlMap">
			<map>
				<entry key="/mytest"><ref local="exampleController"/></entry>
				<entry key="/myform"><ref local="exampleFormController"/></entry>
				<entry key="/mymulti/*"><ref local="exampleMultiController"/></entry>
			</map>
		</property>
	</bean>

	<!--
	  - Explicit view mappings in bundle instead of default InternalResourceViewResolver.
	  - Fetches the view mappings from localized "views_xx" classpath files, i.e.
	  - "/WEB-INF/classes/views.properties" or "/WEB-INF/classes/views_de.properties".
	  -
	  - Symbolic view names returned by controllers will be resolved in the respective
	  - properties file, allowing for arbitrary mappings between names and resources.
	  -->
	<bean id="viewResolver" class="org.springframework.web.servlet.view.ResourceBundleViewResolver">
		<property name="basename"><value>views</value></property>
	</bean>

	<!--
	  - Alternative view resolver, fetching the view mappings from an XML bean
	  - definition file (with <bean ...> syntax) instead of a properties file.
	  - Does not support localized view resolution.
	  -->
	<!--
	<bean id="viewResolver" class="org.springframework.web.servlet.view.XmlViewResolver">
		<property name="location"><value>/WEB-INF/views.xml</value></property>
	</bean>
	-->


	<!-- ========================= CONTROLLER DEFINITIONS ========================= -->

	<!--
	  - Simple Controller implementation, available at /example/mytest
	  - (according to the URL handler mapping definition above).
	  - Uses the ExampleBusinessObject defined in the root application context.
	  -->
	<bean id="exampleController" class="example.ExampleController">
		<property name="businessObject"><ref bean="exampleBusinessObject"/></property>
	</bean>

	<!--
	  - Validator for ExampleFormBean, implementing Spring's Validator interface.
	  - Could also be defined in the root application context, if generic enough.
	  -->
	<bean id="exampleValidator" class="example.ExampleFormBeanValidator"/>

	<!--
	  - SimpleFormController definition, available at /example/myform
	  - (according to the URL handler mapping definition above).
	  - Uses the ExampleFormBeanValidator defined above.
	  -->
	<bean id="exampleFormController" class="org.springframework.web.servlet.mvc.FormControllerTestSuite">
		<property name="beanName"><value>exampleFormBean</value></property>
		<property name="commandClass"><value>example.ExampleFormBean</value></property>
		<property name="validator"><ref local="exampleValidator"/></property>
		<property name="formView"><value>example1</value></property>
		<property name="successView"><value>example2</value></property>
	</bean>

	<!--
	  - Method name resolver definition for MultiActionControllers,
	  - mapping URLs to respective methods of the controller class.
	  -->
	<bean id="exampleMultiMethodNameResolver" class="org.springframework.web.servlet.mvc.multiaction.PropertiesMethodNameResolver">
		<property name="mappings">
			<props>
				<prop key="/mymulti/mycommand1">exampleHandlerMethod</prop>
				<prop key="/mymulti/mycommand2">anotherExampleHandlerMethod</prop>
      </props>
		</property>
	</bean>

	<!--
	  - MultiActionController implementation, available at /example/mymulti/*
	  - (according to the URL handler mapping definition above).
	  - Uses the MethodNameResolver definition defined above.
	  -->
	<bean id="exampleMultiController" class="werk3.example.ExampleMultiController">
		<property name="methodNameResolver"><ref local="exampleMultiMethodNameResolver"/></property>
	</bean>

</beans>

=== cbeams/spring-framework-2.5.x/test/org/springframework/aop/framework/prototypeTests.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC  "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
	Tests for independent prototype behaviour.
-->

<beans>

	<!-- Simple target -->
	<bean id="test" class="org.springframework.aop.interceptor.SideEffectBean">	
		<property name="count"><value>10</value></property>
	</bean>
	
	
	<bean id="prototypeTarget" class="org.springframework.aop.interceptor.SideEffectBean" 
		singleton="false">	
		<property name="count"><value>10</value></property>
	</bean>
	
	
	
	
	<bean id="debugInterceptor" class="org.springframework.aop.interceptor.NopInterceptor">
	</bean>
	
	<bean id="singleton" 
			class="org.springframework.aop.framework.ProxyFactoryBean"
	>	
		<property name="interceptorNames"><value>debugInterceptor,test</value></property>		
		
	</bean>
	

	<bean id="prototype"
		class="org.springframework.aop.framework.ProxyFactoryBean"> 
		<property name="interceptorNames"><value>debugInterceptor,prototypeTarget</value></property>
		<property name="singleton"><value>false</value></property>
	</bean>
	
	<bean id="cglibPrototype"
		class="org.springframework.aop.framework.ProxyFactoryBean"> 
		<property name="interceptorNames"><value>debugInterceptor,prototypeTarget</value></property>
		<property name="singleton"><value>false</value></property>
		
		<!-- Force the use of CGLIB -->
		<property name="proxyTargetClass"><value>true</value></property>

	</bean>
	

</beans>

=== cbeams/spring-framework-2.5.x/test/org/springframework/aop/framework/autoproxy/customTargetSource.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC  "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
	Common bean definitions for EnterpriseServices
	tests.
-->
<beans>

	<bean id="autoproxy"
		class="org.springframework.aop.framework.autoproxy.DefaultAdvisorAutoProxyCreator">
		<property name="customTargetSourceCreators">
			<list>
				<ref local="autoproxy.poolingTargetSourceCreator" />
				<ref local="autoproxy.prototypeTargetSourceCreator" />
			</list>
		</property>
	</bean>
	
	<bean id="autoproxy.poolingTargetSourceCreator"
		class="org.springframework.aop.framework.autoproxy.TestPoolingTargetSourceCreator">
	</bean>
	
	<bean id="autoproxy.prototypeTargetSourceCreator"
		class="org.springframework.aop.framework.autoproxy.SelectivePrototypeTargetSourceCreator">
	</bean>


	<bean id="test" singleton="false"
		class="org.springframework.beans.TestBean">
		<property name="name"><value>Rod</value></property>
		<property name="spouse"><ref local="wife"/></property>
	</bean>
	
	<!-- Prefix will prompt pooling -->
	<bean id="poolingTest" singleton="false"
		class="org.springframework.beans.TestBean">
		<property name="name"><value>Rod</value></property>
		<property name="spouse"><ref local="wife"/></property>
	</bean>
	
	<!-- Prefix will prompt prototype -->
	<bean id="prototypeTest" singleton="false"
		class="org.springframework.beans.TestBean">
		<property name="name"><value>Rod</value></property>
		<property name="spouse"><ref local="wife"/></property>
	</bean>
	
	<bean id="wife"
		class="org.springframework.beans.TestBean">
		<property name="name"><value>Kerry</value></property>
	</bean>
	

</beans>

=== cbeams/spring-framework-2.5.x/test/org/springframework/aop/framework/proxyFactoryTargetSourceTests.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC  "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
	Tests for independent prototype behaviour.
-->

<beans>

	<!-- Simple target -->
	<bean id="target" class="org.springframework.beans.TestBean">	
		<!-- initial value :-) -->
		<property name="name"><value>Adam</value></property>
	</bean>
	
	<bean id="nopInterceptor" class="org.springframework.aop.interceptor.NopInterceptor">
	</bean>
	
	<bean id="countingBeforeAdvice"
		class="org.springframework.aop.framework.CountingBeforeAdvice"
	/>
	
	<!--
		Note that there's normally no reason to create objects of this type
		in a BeanFactory. If for some strange reason you want to, use Type 3 IoC.
	-->
	<bean id="targetSource" class="org.springframework.aop.target.SingletonTargetSource">
		<constructor-arg><ref local="target"/></constructor-arg>
	</bean>

	<bean id="directTarget"
		class="org.springframework.aop.framework.ProxyFactoryBean"> 
		<property name="interceptorNames"><value>countingBeforeAdvice,nopInterceptor,target</value></property>
	</bean>
	
	<bean id="viaTargetSource"
		class="org.springframework.aop.framework.ProxyFactoryBean"> 
		<property name="interceptorNames"><value>nopInterceptor,targetSource</value></property>
	</bean>
	
	<bean id ="unsupportedInterceptor"
		class="org.springframework.aop.framework.UnsupportedInterceptor"
	/>
	
	<!--
		No target or target source, just the interceptor
	-->
	<bean id="noTarget"
		class="org.springframework.aop.framework.ProxyFactoryBean"> 
		<property name="proxyInterfaces"><value>org.springframework.beans.ITestBean</value></property>
		<property name="interceptorNames"><value>nopInterceptor,unsupportedInterceptor</value></property>
	</bean>

</beans>

=== cbeams/spring-framework-2.5.x/samples/imagedb/war/WEB-INF/schedulingContext-quartz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
  - Scheduler context for Quartz. Schedules "list images" and "check images" jobs.
  - Note that Quartz Jobs are throwaway objects, in contrast to shared TimerTasks.
	-->
<beans>

	<!-- Quartz Scheduler, with pre-registered triggers -->
	<!-- Will automatically start scheduling on context startup -->
	<bean id="scheduler" class="org.springframework.scheduling.quartz.SchedulerFactoryBean">
		<property name="triggers">
			<list>
				<ref local="listImagesTrigger"/>
				<ref local="checkImagesTrigger"/>
			</list>
		</property>
	</bean>

	<!-- Job definition for ListImagesQuartzJob -->
	<!-- Lists the images in the image database and sends a corresponding mail -->
	<bean id="listImagesJobDetail" class="org.springframework.scheduling.quartz.JobDetailBean">
		<property name="jobClass">
			<value>org.springframework.samples.imagedb.scheduling.ListImagesQuartzJob</value>
		</property>
		<property name="jobDataAsMap">
			<map>
				<entry key="imageDatabase"><ref bean="imageDatabase"/></entry>
				<entry key="mailSender"><ref bean="mailSender"/></entry>
				<entry key="mailFrom"><value>${mail.from}</value></entry>
				<entry key="mailTo"><value>${mail.to}</value></entry>
			</map>
		</property>
	</bean>

	<!-- Trigger for the job defined above -->
	<!-- Registered by the 'scheduler' bean -->
	<bean id="listImagesTrigger" class="org.springframework.scheduling.quartz.SimpleTriggerBean">
		<property name="jobDetail"><ref bean="listImagesJobDetail"/></property>
		<property name="startDelay"><value>10000</value></property>
		<property name="repeatInterval"><value>10000</value></property>
	</bean>

	<!-- Job definition that delegates to the specified 'imageDatabase' method -->
	<!-- Convenient way of invoking existing business logic instead of writing a job -->
	<bean id="checkImagesJobDetail" class="org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean">
		<property name="targetObject"><ref bean="imageDatabase"/></property>
		<property name="targetMethod"><value>checkImages</value></property>
	</bean>

	<!-- Trigger for the job defined above -->
	<!-- Registered by the 'scheduler' bean -->
	<bean id="checkImagesTrigger" class="org.springframework.scheduling.quartz.CronTriggerBean">
		<property name="jobDetail"><ref bean="checkImagesJobDetail"/></property>
		<property name="cronExpression"><value>0/5 * * * * ?</value></property>
	</bean>

</beans>

=== cbeams/spring-framework-2.5.x/test/org/springframework/aop/framework/proxyFactoryTests.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC  "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>

	<!-- Simple target -->
	<bean id="test" class="org.springframework.beans.TestBean">	
		<property name="name"><value>custom</value></property>
		<property name="age"><value>666</value></property>
	</bean>
	

	
	<bean id="debugInterceptor" class="org.springframework.aop.interceptor.NopInterceptor">
	</bean>
	
	<bean id="test1" 
			class="org.springframework.aop.framework.ProxyFactoryBean"
	>	
		<property name="proxyInterfaces"><value>org.springframework.beans.ITestBean</value></property>		
		
		<property name="target"><ref local="test"/></property>	
		<property name="interceptorNames"><value>debugInterceptor</value></property>		
		
	</bean>
	
	<!--
		Check that invoker is automatically added to wrap target.
		Non pointcut bean name should be wrapped in invoker.
	-->
	<bean id="autoInvoker" 
			class="org.springframework.aop.framework.ProxyFactoryBean"
	>	
		<!-- 
			Aspect interfaces don't need to be included here.
			They may, for example, be added by global interceptors.
		 -->
		<property name="proxyInterfaces"><value>org.springframework.beans.ITestBean</value></property>		
		
		<!--
			Note that "test" is a target. An InvokerInterceptor
			will be added automatically.
		-->
		<property name="interceptorNames"><value>global*,test</value></property>
		
	</bean>
	
	<bean id="prototype" 
			class="org.springframework.aop.framework.ProxyFactoryBean"
	>	
		<property name="proxyInterfaces"><value>org.springframework.beans.ITestBean</value></property>		
		
		<property name="singleton"><value>false</value></property>
		
		<property name="interceptorNames"><value>test</value></property>		
		
	</bean>
	
	<bean id="test2" 
			class="org.springframework.aop.framework.ProxyFactoryBean"
	>	
		<property name="proxyInterfaces"><value>org.springframework.beans.ITestBean</value></property>		
		
		<property name="singleton"><value>false</value></property>
		
		<property name="interceptorNames"><value>test</value></property>		
		
	</bean>
	
	<bean id="pointcuts" 
			class="org.springframework.aop.framework.ProxyFactoryBean"
	>	
		<property name="proxyInterfaces"><value>org.springframework.beans.ITestBean</value></property>		
		
		<property name="interceptorNames"><value>pointcutForVoid,test</value></property>		
		
	</bean>
	
	<bean id="pointcutForVoid"
		class="org.springframework.aop.framework.ProxyFactoryBeanTests$PointcutForVoid"
	>
	</bean>
	
	<!--
		Invalid test for global pointcuts.
		Must have target because there are no interceptors.
	-->
	<!--
	<bean id="noInterceptorNamesWithoutTarget" 
			class="org.springframework.aop.framework.ProxyFactoryBean"
	>	
		<property name="proxyInterfaces"><value>org.springframework.beans.ITestBean</value></property>			
		
	</bean>
	
	<bean id="noInterceptorNamesWithTarget" 
			class="org.springframework.aop.framework.ProxyFactoryBean"
	>	
		<property name="proxyInterfaces"><value>org.springframework.beans.ITestBean</value></property>	
		<property name="target"><ref local="test"/></property>					
		
	</bean>
	-->
	
	<!-- Same effect as noInterceptor names: also invalid -->
	<bean id="emptyInterceptorNames" 
			class="org.springframework.aop.framework.ProxyFactoryBean"
	>	
		<property name="proxyInterfaces"><value>org.springframework.beans.ITestBean</value></property>			
		<property name="interceptorNames"><value> </value></property>
	</bean>
	
	<!--
		Invalid test for global pointcuts.
		Must have target after *.
	-->
	<bean id="globalsWithoutTarget" 
			class="org.springframework.aop.framework.ProxyFactoryBean"
	>	
		<property name="proxyInterfaces"><value>org.springframework.beans.ITestBean</value></property>			
		<property name="interceptorNames"><value>global*</value></property>
	</bean>
	
	
	<bean id="validGlobals" 
			singleton="true"
			class="org.springframework.aop.framework.ProxyFactoryBean"
	>	
		<property name="proxyInterfaces"><value>org.springframework.context.ApplicationListener</value></property>			
		<property name="interceptorNames"><value>debugInterceptor,global*,target2</value></property>
	</bean>
	
	<!--
		Global debug interceptor
	-->
	<bean id="global_debug"
		class="org.springframework.aop.interceptor.DebugInterceptor">
	</bean>
	
	<!--
		Will add aspect interface to all beans exposing globals
	-->
	<bean id="global_aspectInterface"
		class="org.springframework.aop.framework.ProxyFactoryBeanTests$GlobalIntroductionAdvice">
	</bean>
	
	<bean id="target2"
		class="org.springframework.context.event.ConsoleListener">
	</bean>
	
	<bean id="prototypeLockMixinAdvisor" class="org.springframework.aop.framework.LockMixinAdvisor" singleton="false"/>

	<bean id="prototypeTestBean" class="org.springframework.beans.TestBean" singleton="false"/>

	<bean id="prototypeTestBeanProxy" class="org.springframework.aop.framework.ProxyFactoryBean">
		<property name="proxyInterfaces"><value>org.springframework.beans.ITestBean</value></property>
		<property name="singleton"><value>false</value></property>
		<property name="interceptorNames">
			<list>
				<value>prototypeLockMixinAdvisor</value>
				<value>prototypeTestBean</value>
			</list>
		</property>
	</bean>

	<bean id="prototypeLockMixinInterceptor" class="org.springframework.aop.framework.LockMixin" singleton="false"/>

	<bean id="prototypeTestBeanProxySingletonTarget" class="org.springframework.aop.framework.ProxyFactoryBean">
		<property name="proxyInterfaces">
			<list>
				<value>org.springframework.beans.ITestBean</value>
				<value>org.springframework.aop.framework.Lockable</value>
			</list>
		</property>
		<property name="singleton"><value>false</value></property>
		<property name="target"><ref local="prototypeTestBean"/></property>
		<property name="interceptorNames">
			<list>
				<value>prototypeLockMixinInterceptor</value>
			</list>
		</property>
	</bean>

</beans>

=== cbeams/spring-framework-2.5.x/test/org/springframework/beans/factory/xml/dependenciesMaterializeThis.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
  - Replicates a failure because of the dependence of prototype and singleton on
  the dao. Involves factory beans.
  -->

<beans>

	<bean id="dataSource" class="org.apache.commons.dbcp.BasicDataSource"/>

	<bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
		<property name="dataSource"><ref local="dataSource"/></property>
	</bean>
		
	<bean id="dao" class="org.springframework.beans.factory.xml.DummyDao" autowire="constructor"/>

	<bean id="boPrototype" autowire="constructor" class="org.springframework.beans.factory.xml.DummyBoImpl"
		singleton="false"
	/>
	
	<bean id="prototypeTargetSource" class="org.springframework.aop.target.PrototypeTargetSource">
		<property name="targetBeanName"><value>boPrototype</value></property>
	</bean>

	<bean id="prototypeBenchmark" class="org.springframework.transaction.interceptor.TransactionProxyFactoryBean">
		<property name="transactionManager"><ref local="transactionManager"/></property>
		<property name="target"><ref local="prototypeTargetSource"/></property>
		<property name="proxyInterfaces"><value>org.springframework.beans.factory.xml.DummyBo</value></property>
		<property name="transactionAttributes">
			<props>
				<prop key="placeOrder">PROPAGATION_REQUIRED</prop>
			</props>
		</property>
	</bean>

	<bean id="boSingleton" autowire="constructor" class="org.springframework.beans.factory.xml.DummyBoImpl"/>

</beans>
