=== cbeams/spring-framework-2.5.x/src/org/springframework/beans/factory/xml/spring-beans.dtd
<!--
	Spring XML BeanFactory DTD.
	Author: Rod Johnson
	
	This defines a simple and consistent way of creating a namespace
	of JavaBeans configured by a Spring XmlBeanFactory.
	
	This document type is used by most Spring functionality, including
	web application contexts, which are based on BeanFactories.
	
	Each <bean> element in this document defines a JavaBean.
	Typically the bean class is specified, along with JavaBean
	properties.
	
	References among beans are supported (setting a JavaBean
	property to refer to another bean in the same factory).
	
	Bean instances can be "singletons" (shared instances)
	or "prototypes" (independent instances).
	
	There is also support for lists, maps, and 
	java.util.Properties types.
	
	As the format is simple, a DTD is sufficient, and there's
	no need for a schema at this point.
	
	$Id: spring-beans.dtd,v 1.4 2003-10-16 18:56:41 jhoeller Exp $
-->

<!-- 
	The document root.
	At least one bean definition is required.
-->

<!ELEMENT beans (
        bean+
)>

<!--
	Defines a single named bean.
-->
<!ELEMENT bean (
        property*
)>

<!--
	All beans are identified by an id, to enable reference checking.
	There are constraints on a valid XML id: if you want to reference
	your bean in Java code using a name that's illegal as an XML id,
	use the optional "name" attribute.
-->
<!ATTLIST bean id ID #REQUIRED>

<!-- 
	Each bean definition must specify the FQN of the class,
	or the name of the parent bean from which the class can be worked out.
-->
<!ATTLIST bean class CDATA #IMPLIED>
<!ATTLIST bean parent CDATA #IMPLIED>

<!--
	Optional attribute controlling whether to check whether all this
	beans dependencies, expressed in its properties, are satisfied.
	Default is no dependency checking.
	"simple" type dependency checking includes primitives and String
	"object" includes collaborators (other beans in the factory)
	"all" includes both types of dependency checking
	
-->
<!ATTLIST bean dependency-check (none|objects|simple|all) "none">

<!--
	Optional attribute controlling whether to "autowire"
	bean properties. This is an automagical process in which bean references
	don't need to be coded explicitly in the XML bean definition file,
	but Spring works out dependencies.
	
	There are three modes:
	
	1. no
	The traditional Spring default. No automagical wiring. Bean references
	must be defined in the XML file via the <ref> element. We recommend this
	in most cases as it makes documentation more explicit.
	
	2. byName
	Autowiring by property name. If a bean of class Cat exposes a dog property,
	Spring will try to set this to the value of the bean "dog" in the current
	factory.
	
	3. byType
	This is like the PicoContainer default, in which there must be exactly
	one bean of the property type in the bean factory. If there are 0 or
	more than one, a fatal error is raised, and you can't use byType autowiring for
	that bean.
	This makes bean factories simple to configure for small namespaces,
	but doesn't work as well as standard Spring behaviour for
	bigger applications.
	
	Autowire behaviour can be combined with dependency checking, which will
	be performed after all auto wiring has been completed.
-->
<!ATTLIST bean autowire (no|byName|byType) "no"> 

<!-- 
	Optional attribute for the name of the custom initialization method
	to invoke after setting bean properties. The method must have no arguments,
	but may throw any exception. 
-->
<!ATTLIST bean init-method CDATA #IMPLIED>

<!--
	Optional attribute for the name of the custom destroy method to invoke
	on bean factory shutdown. The method must have no arguments,
	but may throw any exception. Note: Only invoked on singleton beans!
-->
<!ATTLIST bean destroy-method CDATA #IMPLIED>

<!--
	Is this bean a "singleton" (one shared instance, which will
	be returned by all calls to getBean() with the id),
	or a "prototype" (independent instance resulting from each call to
	getBean(). Default is singleton.

	Singletons are most commonly used, and are ideal for multi-threaded
	service objects.
-->
<!ATTLIST bean singleton (true|false) "true"> 

<!--
	Optional. Can be used to create an alias illegal in an id.
-->
<!ATTLIST bean name CDATA #IMPLIED>

<!--
	Bean definitions can have zero or more properties. 
	Property elements correspond to JavaBean setter methods exposed
	by the bean classes. Spring supports primitives, references to other
	beans in the same or related factories, lists, maps and properties.
-->
<!ELEMENT property (
        (value | ref | list | map | props)
)>

<!--
	The property name attribute is the name of the JavaBean property.
	This follows JavaBean conventions: a name of "age" would correspond
	to setAge()/optional getAge() methods.
-->
<!ATTLIST property name CDATA #REQUIRED>

<!--
	Defines a reference to another bean in this factory or an external
	factory (parent or included factory). 
-->
<!ELEMENT ref EMPTY>

<!--
	Contains a string representation of a property value.
	The property may be a string, or may be converted to the
	required type using the JavaBeans PropertyEditor
	machinery. This makes it possible for application developers
	to write custom PropertyEditor implementations that can
	convert strings to objects. 
	
	Note that this is recommended for simple objects only.
	Configure more complex objects by setting JavaBean
	properties to references to other beans.
-->
<!ELEMENT value (#PCDATA)>

<!-- 
	References must specify the id of the target bean.
	Internal references, using
	the "bean" attribute, can be checked by this DTD,
	thus should be preferred for references within the same
	bean factory XML file.
	External references must use the "external" attribute and can
	be checked only at runtime.
-->
<!ATTLIST ref bean IDREF #IMPLIED>
<!ATTLIST ref external CDATA #IMPLIED>

<!--
	A list can contain multiple value and/or ref elements.
	Java lists are untyped, pending generics support in Java 1.5. 
	although references will be strongly typed. 
	A list can also map to an array type. The necessary conversion
	is automatically performed by the Spring AbstractBeanFactory. 
-->
<!ELEMENT list (
        (value | ref)*
)>

<!--
	A Spring map is a mapping from a string key to 
	object.
	Maps may be empty.
-->
<!ELEMENT map (
        (entry)*
)>

<!--
	A map entry can be a value, ref or list
	The name of the property is given by the "key" attribute.
-->
<!ELEMENT entry (
        (value | ref | list)*
)>

<!ATTLIST entry key CDATA #REQUIRED>

<!--
	Props elements differ from map elements in that values must be strings.
	Props may be empty.
-->
<!ELEMENT props (
        (prop)*
)>

<!--
	Element content is the string value of the property. The "key"
	attribute is the name of the property.
-->
<!ELEMENT prop
        (#PCDATA)
>

<!--
	Each property element must specify the key. The value
	is the element content.
-->
<!ATTLIST prop key CDATA #REQUIRED>

=== cbeams/spring-framework-2.5.x/test/org/springframework/context/support/childWithProxy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC  "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>

	<bean name="assemblerOne" class="org.springframework.transaction.interceptor.TransactionProxyFactoryBean">
		<property name="transactionManager"><ref bean="transactionManager"/></property>
		<property name="target"><ref parent="assemblerOne"/></property>
		<property name="proxyTargetClass"><value>true</value></property>
		<property name="transactionAttributes">
			<props>
				<prop key="test">PROPAGATION_REQUIRED</prop>
			</props>
		</property>
	</bean>

	<bean name="assemblerTwo" class="org.springframework.transaction.interceptor.TransactionProxyFactoryBean">
		<property name="transactionManager"><ref bean="transactionManager"/></property>
		<property name="target"><ref parent="assemblerTwo"/></property>
		<property name="proxyTargetClass"><value>true</value></property>
		<property name="transactionAttributes">
			<props>
				<prop key="test">PROPAGATION_REQUIRED</prop>
			</props>
		</property>
	</bean>

</beans>

=== cbeams/spring-framework-2.5.x/samples/showcases/formtags/war/WEB-INF/formtags-servlet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN"
        "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>

    <bean id="viewResolver" class="org.springframework.web.servlet.view.InternalResourceViewResolver">
        <property name="prefix" value="/WEB-INF/jsp/"/>
        <property name="suffix" value=".jsp"/>
    </bean>

    <bean name="/list.htm" class="org.springframework.showcase.formtags.web.ListController">
        <property name="userManager" ref="userManager"/>
    </bean>

    <bean name="/form.htm" class="org.springframework.showcase.formtags.web.FormController">
        <property name="formView" value="form"/>
        <property name="successView" value="redirect:list.htm"/>
        <property name="userManager" ref="userManager"/>
        <property name="validators" ref="userValidator"/>
    </bean>

    <bean name="/about.htm" class="org.springframework.showcase.formtags.web.ListController">
        <property name="userManager" ref="userManager"/>
        <property name="viewName" value="about"/>
    </bean>

    <bean id="userValidator" class="org.springframework.showcase.formtags.validation.UserValidator">
        <property name="countryValidator">
            <bean class="org.springframework.showcase.formtags.validation.CountryValidator"/>
        </property>
    </bean>

</beans>

=== cbeams/spring-framework-2.5.x/test/org/springframework/beans/factory/support/root.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC  "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>

	<bean id="defaultAttributeRegistry" class="org.springframework.aop.attributes.MapAttributeRegistry">	
	
	</bean>
	
	
	<bean id="demoController"
		 class="org.springframework.web.servlet.mvc.DemoController">	
	
	</bean>
	
	<!-- Overridden by next factory -->
	<bean id="test" class="org.springframework.beans.TestBean">	
		<property name="name"><value>custom</value></property>
		<property name="age"><value>25</value></property>
	</bean>

</beans>

=== cbeams/spring-framework-2.5.x/samples/petclinic/war/WEB-INF/applicationContext-jdbc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
  - Application context definition for PetClinic on JDBC.
  -->
<beans>

	<!-- ========================= RESOURCE DEFINITIONS ========================= -->
  
	<!-- Configurer that replaces ${...} placeholders with values from a properties file -->
	<!-- (in this case, JDBC-related settings for the dataSource definition below) -->
	<bean id="propertyConfigurer" class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
		<property name="location" value="/WEB-INF/jdbc.properties"/>
	</bean>

	<!-- 
		Simple local DataSource that works in any environment.
		This uses the JDBC DriverManager to obtain connections, and does NOT perform connection
		pooling. Connection pooling is essential to all real-world applications.
		This definition is good for getting started, as it introduces no dependencies beyond
		the JDK, but DriverManagerDataSource is not intended for production usage.
	 -->
	<bean id="dataSource" class="org.springframework.jdbc.datasource.DriverManagerDataSource">
		<property name="driverClassName" value="${jdbc.driverClassName}"/>
		<property name="url" value="${jdbc.url}"/>
		<property name="username" value="${jdbc.username}"/>
		<property name="password" value="${jdbc.password}"/>
	</bean>
	
	<!-- 
		Alternative local DataSource that works in any environment, and offers much better performance.
		Uses Apache Commons DBCP for connection pooling. See Commons DBCP documentation
		for the required JAR files. See the PetStore sample application also shipped with
		Spring, for an example of Commons DBCP usage and the necessary build script.
		Alternatively you can use another connection pool such as C3P0, similarly configured
		using Spring.
		A standalone connection pool such as Commons DBCP is a good choice for use outside an
		application server environment, including web applications running in a web container without
		JTA, or integration testing using the org.springframework.test package.
	 -->
	<!--
	<bean id="dataSource" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
		<property name="driverClassName" value="${jdbc.driverClassName}"/>
		<property name="url" value="${jdbc.url}"/>
		<property name="username" value="${jdbc.username}"/>
		<property name="password" value="${jdbc.password}"/>
	</bean>
	-->

	<!-- JNDI DataSource for J2EE environments -->
	<!--
	<bean id="dataSource" class="org.springframework.jndi.JndiObjectFactoryBean">
		<property name="jndiName" value="java:comp/env/jdbc/petclinic"/>
	</bean>
	-->

	<!-- Transaction manager for a single JDBC DataSource (alternative to JTA) -->
	<bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
		<property name="dataSource" ref="dataSource"/>
	</bean>

	<!-- Transaction manager that delegates to JTA (for a transactional JNDI DataSource) -->
	<!--
	<bean id="transactionManager" class="org.springframework.transaction.jta.JtaTransactionManager"/>
	-->


	<!-- ========================= BUSINESS OBJECT DEFINITIONS ========================= -->

	<!-- PetClinic's central data access object: HSQL JDBC implementation -->
	<!-- (only initialized when referenced by the "clinic" proxy) -->
	<bean id="hsqlClinic" class="org.springframework.samples.petclinic.jdbc.HsqlJdbcClinic" lazy-init="true">
		<property name="dataSource" ref="dataSource"/>
	</bean>

	<!-- PetClinic's central data access object: MySQL JDBC implementation -->
	<!-- (only initialized when referenced by the "clinic" proxy) -->
	<bean id="mysqlClinic" class="org.springframework.samples.petclinic.jdbc.MySQLJdbcClinic" lazy-init="true">
		<property name="dataSource" ref="dataSource"/>
	</bean>

	<!--
		- Transactional proxy for PetClinic's central data access facade.
		- Implements the CachingClinic management interface.
		-
		- Note that in a real-life app with multiple transaction proxies,
		- you will probably want to use parent and child bean definitions
		- as described in the manual, to reduce duplication.
    -->
	<bean id="clinic" class="org.springframework.transaction.interceptor.TransactionProxyFactoryBean">
		<property name="transactionManager" ref="transactionManager"/>
		<property name="target" ref="${petclinic.jdbcImplBeanName}"/>
		<property name="transactionAttributes">
			<props>
				<prop key="*">PROPAGATION_REQUIRED</prop>
			</props>
		</property>
		<property name="preInterceptors" ref="callMonitor"/>
	</bean>

	<!-- Call monitoring interceptor that monitors call count and call invocation time -->
	<!-- Implements the CallMonitor management interface -->
	<bean id="callMonitor" class="org.springframework.samples.petclinic.jmx.CallMonitoringInterceptor"/>


	<!-- ========================= JMX EXPORTER DEFINITION ========================= -->

	<!--
	  - Exporter that exposes both the CachingClinic and the CallMonitor via JMX.
		-
		- By default, the standard MBeanServerFactory.findMBeanServer method will be used
		- to determine the MBeanServer. Unfortunately, this does not work on WebLogic <= 8.1:
		- you need to comment in the WebLogicMBeanServerFactoryBean definition on WebLogic,
		- specifying appropriate configuration values there.
		-
		- Note that you need to comment in the "defaultCurrencyTimeLimit" value on JBoss 3.x.
    -->
	<bean id="jmxExporter" class="org.springframework.jmx.export.MBeanExporter">
		<property name="beans">
			<map>
				<entry key="petclinic:service=clinic" value-ref="clinic"/>
				<entry key="petclinic:service=callMonitor" value-ref="callMonitor"/>
			</map>
		</property>
		<property name="assembler">
			<bean class="org.springframework.jmx.export.assembler.InterfaceBasedMBeanInfoAssembler">
				<property name="interfaceMappings">
					<props>
						<prop key="petclinic:service=clinic">org.springframework.samples.petclinic.jdbc.CachingClinic</prop>
						<prop key="petclinic:service=callMonitor">org.springframework.samples.petclinic.jmx.CallMonitor</prop>
					</props>
				</property>
				<!-- Comment the following in on JBoss 3.x, which doesn't follow -->
				<!-- the JMX 1.2 recommendation for currencyTimeLimit behavior. -->
				<!--
				<property name="defaultCurrencyTimeLimit" value="0"/>
				-->
			</bean>
		</property>
		<!-- Comment the following in on WebLogic <= 8.1, which doesn't support -->
		<!-- the standard MBeanServerFactory.findMBeanServer lookup mechanism. -->
		<!--
		<property name="server">
			<bean class="org.springframework.jmx.support.WebLogicMBeanServerFactoryBean">
				<property name="username" value="weblogic"/>
				<property name="password" value="weblogic"/>
				<property name="serverUrl" value="t3://localhost:7001"/>
				<property name="serverName" value="server"/>
			</bean>
		</property>
		-->
	</bean>

</beans>

=== cbeams/spring-framework-2.5.x/samples/jpetstore/war/WEB-INF/dataAccessContext-local.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
  - Application context definition for JPetStore's data access layer.
	- Accessed by business layer objects defined in "applicationContext.xml"
	- (see web.xml's "contextConfigLocation").
	-
	- This version of the data access layer works on a combined database,
	- using a local DataSource with DataSourceTransactionManager. It does not
	- need any JTA support in the container: It will run as-is in plain Tomcat.
	-->
<beans>

	<!-- ========================= RESOURCE DEFINITIONS ========================= -->

	<!-- Local DataSource that refers to a combined database -->
	<!-- (see dataAccessContext-jta.xml for an alternative) -->
	<!-- The placeholders are resolved from jdbc.properties through -->
	<!-- the PropertyPlaceholderConfigurer in applicationContext.xml -->
	<bean id="dataSource" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
		<property name="driverClassName"><value>${jdbc.driverClassName}</value></property>
		<property name="url"><value>${jdbc.url}</value></property>
		<property name="username"><value>${jdbc.username}</value></property>
		<property name="password"><value>${jdbc.password}</value></property>
	</bean>

	<!-- Transaction manager for a single JDBC DataSource -->
	<!-- (see dataAccessContext-jta.xml for an alternative) -->
	<bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
		<property name="dataSource"><ref local="dataSource"/></property>
	</bean>

	<!-- SqlMap setup for iBATIS Database Layer -->
	<bean id="sqlMapClient" class="org.springframework.orm.ibatis.SqlMapClientFactoryBean">
		<property name="configLocation"><value>WEB-INF/sql-map-config.xml</value></property>
		<property name="dataSource"><ref local="dataSource"/></property>
	</bean>


	<!-- ========================= DAO DEFINITIONS: IBATIS IMPLEMENTATIONS ========================= -->

	<bean id="accountDao" class="org.springframework.samples.jpetstore.dao.ibatis.SqlMapAccountDao">
		<property name="sqlMapClient"><ref local="sqlMapClient"/></property>
	</bean>

	<bean id="categoryDao" class="org.springframework.samples.jpetstore.dao.ibatis.SqlMapCategoryDao">
		<property name="sqlMapClient"><ref local="sqlMapClient"/></property>
	</bean>

	<bean id="productDao" class="org.springframework.samples.jpetstore.dao.ibatis.SqlMapProductDao">
		<property name="sqlMapClient"><ref local="sqlMapClient"/></property>
	</bean>

	<bean id="itemDao" class="org.springframework.samples.jpetstore.dao.ibatis.SqlMapItemDao">
		<property name="sqlMapClient"><ref local="sqlMapClient"/></property>
	</bean>

	<!-- Refers to the combined database here -->
	<!-- (see dataAccessContext-jta.xml for an alternative) -->
	<bean id="orderDao" class="org.springframework.samples.jpetstore.dao.ibatis.SqlMapOrderDao">
		<property name="sqlMapClient"><ref local="sqlMapClient"/></property>
		<property name="sequenceDao"><ref local="sequenceDao"/></property>
	</bean>

	<!-- OrderDao definition for MS SQL Server -->
	<!-- (to be used instead of the default orderDao) -->
	<!--
	<bean id="orderDao" class="org.springframework.samples.jpetstore.dao.ibatis.MsSqlOrderDao">
		<property name="sqlMapClient"><ref local="sqlMapClient"/></property>
		<property name="sequenceDao"><ref local="sequenceDao"/></property>
	</bean>
	-->

	<!-- Refers to the combined database here -->
	<!-- (see dataAccessContext-jta.xml for an alternative) -->
	<bean id="sequenceDao" class="org.springframework.samples.jpetstore.dao.ibatis.SqlMapSequenceDao">
		<property name="sqlMapClient"><ref local="sqlMapClient"/></property>
	</bean>

	<!-- SequenceDao definition for Oracle databases -->
	<!-- (to be used instead of the default sequenceDao) -->
	<!--
	<bean id="sequenceDao" class="org.springframework.samples.jpetstore.dao.ibatis.OracleSequenceDao">
		<property name="sqlMapClient"><ref local="sqlMapClient"/></property>
	</bean>
	-->

</beans>

=== cbeams/spring-framework-2.5.x/test/org/springframework/beans/factory/access/beans2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: beans2.xml,v 1.1 2004-01-27 00:03:45 colins Exp $ -->
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>

  <bean id="beans2.bean1" class="org.springframework.beans.factory.access.TestBean">
    <property name="name"><value>beans2.bean1</value></property>
  </bean>

  <bean id="beans2.bean2" class="org.springframework.beans.factory.access.TestBean">
    <property name="name"><value>beans2.bean2</value></property>
    <property name="objRef"><ref bean="beans1.bean1"/></property>
  </bean>
 
</beans>

=== cbeams/spring-framework-2.5.x/samples/jpetstore/war/WEB-INF/remoting-servlet.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
	- Dispatcher servlet for HTTP remoting via Hessian, Burlap, and Spring's
	- HTTP invoker (see remoting-servlet.xml for the controllers).
	-->
<beans>

	<!-- Hessian exporter for the JPetStore OrderService -->
	<!-- Hessian is a slim binary HTTP remoting protocol -->
	<bean name="/OrderService-hessian" class="org.springframework.remoting.caucho.HessianServiceExporter">
		<property name="service"><ref bean="petStore"/></property>
		<property name="serviceInterface">
			<value>org.springframework.samples.jpetstore.domain.logic.OrderService</value>
		</property>
	</bean>

	<!-- Burlap exporter for the JPetStore OrderService -->
	<!-- Burlap is a slim XML-based HTTP remoting protocol -->
	<bean name="/OrderService-burlap" class="org.springframework.remoting.caucho.BurlapServiceExporter">
		<property name="service"><ref bean="petStore"/></property>
		<property name="serviceInterface">
			<value>org.springframework.samples.jpetstore.domain.logic.OrderService</value>
		</property>
	</bean>

	<!-- HTTP invoker exporter for the JPetStore OrderService -->
	<!-- Spring's HTTP invoker uses Java serialization via HTTP  -->
	<bean name="/OrderService-httpinvoker" class="org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter">
		<property name="service"><ref bean="petStore"/></property>
		<property name="serviceInterface">
			<value>org.springframework.samples.jpetstore.domain.logic.OrderService</value>
		</property>
	</bean>

</beans>

=== cbeams/spring-framework-2.5.x/test/org/springframework/beans/factory/xml/parent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC  "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>

	<bean id="inheritedTestBean" class="org.springframework.beans.TestBean" abstract="true">
		<property name="name"><value>parent</value></property>
		<property name="age"><value>1</value></property>
	</bean>
	
	<bean id="inheritedTestBeanWithoutClass" abstract="true">
		<property name="name"><value>parent</value></property>
		<property name="age"><value>1</value></property>
	</bean>

	<bean id="inheritedTestBeanPrototype" class="org.springframework.beans.TestBean" singleton="false">
		<property name="name"><value>parent</value></property>
		<property name="age"><value>2</value></property>
	</bean>

</beans>
